name: Test Orchestrator

# Allows a “Run workflow” button in the Actions tab
on:
  workflow_dispatch: {}

jobs:
  units:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Units repo
        uses: actions/checkout@v4

              # ---- your tests go here ----
        with:
          repository: JeffCompasClassrooms/testing-units-f25-gisela-codes
          path: units
      - name: Install dependencies
        run: pip install pytest pytest-spec pytest-describe coverage
      - name: Run tests
        working-directory: units
        run: pytest --spec
        continue-on-error: true

      - name: Run coverage
        working-directory: units
        run: |
          coverage run -m pytest
          coverage report -m

  systems:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Systems repo
        uses: actions/checkout@v4
        with:
          repository: JeffCompasClassrooms/testing-systems-gisela-codes
          path: systems
      - name: Install dependencies
        run: pip install pytest pytest-spec pytest-describe coverage
      - name: Run tests
        working-directory: systems
        run: pytest --spec
        continue-on-error: true

      - name: Run coverage
        working-directory: systems
        run: |
          coverage run -m pytest
          coverage report -m
        continue-on-error: true

  behave:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Behave repo
        uses: actions/checkout@v4
        with:
          repository: JeffCompasClassrooms/testing-with-behave-gisela-codes
          path: behave
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        working-directory: behave
        run: |
          python -m pip install --upgrade pip
          pip install behave==1.2.6 selenium==3.141.0 urllib3==1.26.15 behave-webdriver
      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      - name: Run Behave 
        run: |
          behave isitchristmas/features
          behave peppers-ghost/features
          behave time/features
          behave primes/features
