name: Test Orchestrator

# Allows a “Run workflow” button in the Actions tab
on:
  workflow_dispatch: {}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---- your tests go here ----
      - name: Run test for repo 
        run: |
          echo "Running tests..."
          # replace this line with your actual test command(s)

      - name: Checkout Units repo
        uses: actions/checkout@v4
        with:
          repository: JeffCompasClassrooms/testing-units-f25-gisela-codes
          path: JeffCompasClassrooms/testing-units-f25-gisela-codes
      
      - name: Install dependencies
        run: pip install pytest pytest-spec pytest-describe coverage
      
      - name: run test
        run: pytest --spec
        continue-on-error: true

      - name: run coverage
        run: |
          coverage run -m pytest
          coverage report -m
        continue-on-error: true

      - name: Checkout Systems repo
        uses: actions/checkout@v4
        with:
          repository: JeffCompasClassrooms/testing-systems-gisela-codes
          path: JeffCompasClassrooms/testing-systems-gisela-codes
      
      - name: Install dependencies
        run: pip install pytest pytest-spec pytest-describe coverage
      
      - name: run test
        run: pytest --spec
        continue-on-error: true

      - name: run coverage
        run: |
          coverage run -m pytest
          coverage report -m
        continue-on-error: true

      - name: Checkout Systems repo
        uses: actions/checkout@v4
        with:
          repository: JeffCompasClassrooms/testing-with-behave-gisela-codes
          path: JeffCompasClassrooms/testing-with-behave-gisela-codes
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install behave==1.2.6 selenium==3.141.0 urllib3==1.26.15 behave-webdriver

      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run Behave isitchristmas
        working-directory: isitchristmas
        run: behave